### ISSUE TITLE
pull_config.py: Missing required arguments when calling "pull" functions under go() function

### ISSUE THREAD

**Issue by pwalker99** [ktanushree/prismasdwan_policy_config#2]
The following functions require an argument called reset_config **pull_policy_path, pull_policy_qos, pull_policy_security, pull_policy_nat**, but under the go() function starting at line 2160 these functions are called without the required argument, producing the error below: 

```
$ python3 pull_policy.py -PT path --output production_policy.yml
INFO: Building translation dicts
Traceback (most recent call last):
  File "/home/ec2-user/prismasdwan_policy_config/pull_policy.py", line 2207, in <module>
    go()
  File "/home/ec2-user/prismasdwan_policy_config/pull_policy.py", line 2163, in go
    pull_policy_path(cgx_session=cgx_session, config_file=filename)
TypeError: pull_policy_path() missing 1 required positional argument: 'reset_config'

```

**Comment by ktanushree** [comment]
Hi @pwalker99 this is fixed in 1.0.0b3. Thanks!
